### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lobothijau** [lobothijau/bukusakuandroid#1]
## Recyclerview
- [ ] Mengaktifkan divider (garis pemisah) antar item 
- [ ] Menganimasikan perubahan data
- [ ] Menampilkan menu popup di Item RecyclerView
- [ ] Menghapus data dengan swipe
- [ ] Melakukan drag & drop
- [ ] Menampilkan iklan diantara item
- [ ] Mengaktifkan endless scrolling

## Intent
- [ ] Membuka Activity baru
- [ ] Menerima data dari Activity baru
- [ ] Membuka URL di Browser
- [ ] Membuka Aplikasi Map dengan lokasi tertentu
- [ ] Membuka Aplikasi Navigation dengan tujuan
- [ ] Mengirimkan email
- [ ] Mengambil foto
- [ ] Splash Screen

## SharedPreferences
- [ ] Dasar-dasar penggunaan SharedPreferences
- [ ]  Membuat halaman Settings dengan SharedPreferences

## Google Maps API v2
- [ ] Menampilkan maps
- [ ]  Mengatur posisi kamera maps
- [ ] Menampilkan lokasi saat ini di maps

## Internet - Retrofit
- [ ] Melakukan request GET
- [ ] Melakukan request POST
- [ ] Mengunggah file
- [ ] Mengunduh file
- [ ] Menggunakan logging interceptor untuk debugging
- [ ] Otentikasi dengan Header
- [ ] Custom JSON parser

## Permission
- [ ] Meminta permission di Android 6.0 ke atas
- [ ] Menggunakan Easy Permission

## Database (Dear Diary)
- [ ] SQLite
- [ ] Room
- [ ] Realm
- [ ] ObjectBox

## Fragment
- [ ] Membuat dan menggunakan fragment
- [ ] Menampilkan dan menyembunyikan fragment saat runtime
- [ ] Mengirim data antar fragment
- [ ] Mengirim data antara fragment dan activity

## File
- [ ] Baca tulis file di internal storage
- [ ] Baca tulis file di external storage

## Alert/Dialog
- [ ] Toast
- [ ] Custom Toast
- [ ] Progress 

## Audio/Video
- [ ] MediaPlayer
- [ ] ExoPlayer

## WebView
- [ ] Menampilkan URL
- [ ] Menampilkan asset lokal
- [ ] Meng-intercept event WebView
- [ ] Mengaktifkan JavaScript

## DownloadManager
- [ ] Mengunduh file di belakang layar

## JSON
- [ ] Parsing dengan JSONObject
- [ ] Buat JSON dengan JSONObject
- [ ] GSON
- [ ] Jackson
- [ ] Moshi

## XML
- [ ] Parsing XML

## SMS
- [ ] Menerima SMS
- [ ] Mengirim SMS
